-- CreateTable
CREATE TABLE "UserInfo" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "language" TEXT,
    "screenSize" TEXT,
    "timezone" TEXT,
    "platform" TEXT,
    "browser" TEXT,
    "referrer" TEXT,
    "location" TEXT,
    "visitedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "country" TEXT,
    "city" TEXT,
    "device" TEXT,
    "osName" TEXT,
    "osVersion" TEXT,
    "browserVersion" TEXT,
    "webGLRenderer" TEXT,
    "cpuCores" INTEGER,
    "ram" TEXT,
    "cookiesEnabled" BOOLEAN,
    "localStorageAvailable" BOOLEAN,
    "sessionStorageAvailable" BOOLEAN,
    "connectionType" TEXT,
    "batteryLevel" REAL,
    "batteryCharging" BOOLEAN,
    "orientation" TEXT,
    "touchScreen" BOOLEAN,
    "additionalData" JSONB
);
